server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  server:
    password: "aimbot1129"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

    spotify:
      clientId: "aa5706fb4367451aa52c63bb95f9e4d6"
      clientSecret: "c056dcb5cfc14f1aa7682cd393f9833b"
      countryCode: "nz"

    timeouts:
      connectTimeoutMs: 3000
      connectionRequestTimeoutMs: 3000
      socketTimeoutMs: 3000
